version: "3"
services:
  document-generator-app:
    image: document-generator
    environment:
      - API_PREFIX=/api/v1
      - BACKEND_CORS_ORIGINS=
      - LOCAL_STORAGE_TEMPLATE_PATH=templates
      - LOCAL_STORAGE_TMP_PATH=tmp
    volumes:
      - document-generator-volume:/code/templates
    ports:
      - "4444:80"
