"""
This type stub file was generated by pyright.
"""

"""This module does the actual generation of the QR codes. The QRCodeBuilder
builds the code. While the various output methods draw the code into a file.
"""
class QRCodeBuilder:
    """This class generates a QR code based on the standard. It is meant to
    be used internally, not by users!!!

    This class implements the tutorials found at:

    * http://www.thonky.com/qr-code-tutorial/

    * http://www.matchadesign.com/blog/qr-code-demystified-part-6/

    This class also uses the standard, which can be read online at:
        http://raidenii.net/files/datasheets/misc/qr_code.pdf

    Test codes were tested against:
        http://zxing.org/w/decode.jspx

    Also, reference codes were generat/ed at:
        http://www.morovia.com/free-online-barcode-generator/qrcode-maker.php
        http://demos.telerik.com/aspnet-ajax/barcode/examples/qrcode/defaultcs.aspx

    QR code Debugger:
        http://qrlogo.kaarposoft.dk/qrdecode.html
    """
    def __init__(self, data, version, mode, error) -> None:
        """See :py:class:`pyqrcode.QRCode` for information on the parameters."""
        ...
    
    def grouper(self, n, iterable, fillvalue=...): # -> zip_longest[Any]:
        """This generator yields a set of tuples, where the
        iterable is broken into n sized chunks. If the
        iterable is not evenly sized then fillvalue will
        be appended to the last tuple to make up the difference.

        This function is copied from the standard docs on
        itertools.
        """
        ...
    
    def binary_string(self, data, length): # -> str:
        """This method returns a string of length n that is the binary
        representation of the given data. This function is used to
        basically create bit fields of a given size.
        """
        ...
    
    def get_data_length(self): # -> str:
        """QR codes contain a "data length" field. This method creates this
        field. A binary string representing the appropriate length is
        returned.
        """
        ...
    
    def encode(self): # -> str:
        """This method encodes the data into a binary string using
        the appropriate algorithm specified by the mode.
        """
        ...
    
    def encode_alphanumeric(self): # -> str:
        """This method encodes the QR code's data if its mode is
        alphanumeric. It returns the data encoded as a binary string.
        """
        ...
    
    def encode_numeric(self): # -> str:
        """This method encodes the QR code's data if its mode is
        numeric. It returns the data encoded as a binary string.
        """
        ...
    
    def encode_bytes(self): # -> str:
        """This method encodes the QR code's data if its mode is
        8 bit mode. It returns the data encoded as a binary string.
        """
        ...
    
    def encode_kanji(self): # -> str:
        """This method encodes the QR code's data if its mode is
        kanji. It returns the data encoded as a binary string.
        """
        ...
    
    def add_data(self): # -> None:
        """This function properly constructs a QR code's data string. It takes
        into account the interleaving pattern required by the standard.
        """
        ...
    
    def terminate_bits(self, payload): # -> str | None:
        """This method adds zeros to the end of the encoded data so that the
        encoded data is of the correct length. It returns a binary string
        containing the bits to be added.
        """
        ...
    
    def delimit_words(self): # -> str | None:
        """This method takes the existing encoded binary string
        and returns a binary string that will pad it such that
        the encoded string contains only full bytes.
        """
        ...
    
    def add_words(self): # -> str | None:
        """The data block must fill the entire data capacity of the QR code.
        If we fall short, then we must add bytes to the end of the encoded
        data field. The value of these bytes are specified in the standard.
        """
        ...
    
    def make_error_block(self, block, block_number):
        """This function constructs the error correction block of the
        given data block. This is *very complicated* process. To
        understand the code you need to read:

        * http://www.thonky.com/qr-code-tutorial/part-2-error-correction/
        * http://www.matchadesign.com/blog/qr-code-demystified-part-4/
        """
        ...
    
    def make_code(self): # -> None:
        """This method returns the best possible QR code."""
        ...
    
    def add_detection_pattern(self, m): # -> None:
        """This method add the detection patterns to the QR code. This lets
        the scanner orient the pattern. It is required for all QR codes.
        The detection pattern consists of three boxes located at the upper
        left, upper right, and lower left corners of the matrix. Also, two
        special lines called the timing pattern is also necessary. Finally,
        a single black pixel is added just above the lower left black box.
        """
        ...
    
    def add_position_pattern(self, m): # -> None:
        """This method draws the position adjustment patterns onto the QR
        Code. All QR code versions larger than one require these special boxes
        called position adjustment patterns.
        """
        ...
    
    def add_version_pattern(self, m): # -> None:
        """For QR codes with a version 7 or higher, a special pattern
        specifying the code's version is required.

        For further information see:
        http://www.thonky.com/qr-code-tutorial/format-version-information/#example-of-version-7-information-string
        """
        ...
    
    def make_masks(self, template): # -> list[str]:
        """This method generates all seven masks so that the best mask can
        be determined. The template parameter is a code matrix that will
        server as the base for all the generated masks.
        """
        ...
    
    def choose_best_mask(self): # -> int:
        """This method returns the index of the "best" mask as defined by
        having the lowest total penalty score. The penalty rules are defined
        by the standard. The mask with the lowest total score should be the
        easiest to read by optical scanners.
        """
        ...
    
    def add_type_pattern(self, m, type_bits): # -> None:
        """This will add the pattern to the QR code that represents the error
        level and the type of mask used to make the code.
        """
        ...
    


